### PR TITLE
Start Java 8 Clean Up

### PR DESCRIPTION
**Pull request by c3ccl3ston**
Remove selenium3.junit4.examples.cucumber as items already existed in selenium-examples

@nadvolod - I was not sure what to do with JUnit3UpdateSauceStatusTest.java as it is referencing JUnit 3 and does not have any test annotations and therefore did not execute any tests. I have not updated the README.md with that as an example because I figure that it either needs to be updated or removed. Please let me know your thoughts.

### CODE REVIEW

**Comment by nadvolod** [comment]
@c3ccl3ston yea, that was a request for a large customer that's still on Junit 3 and unfortunately I think that we need to keep it. It should have worked for you though. You tried to run it and it didn't work? Junit3 doesn't have annotations actually and only works when you mention "test" in the name... Crazy stuff haha. I guess just create a new module called `selenium-junit3-examples` and stick this one in there please

**Review by nadvolod — COMMENTED** [review]
I added a comment on what I think we should do

**Comment by c3ccl3ston** [comment]
Thanks @nadvolod! I have updated the README.md with the JUnit 3 example and yes, I was able to execute the tests. As for the remaining Selenium 4 folder under Java 8, I will need some time as I am not yet familiar with some of the Selenium 4 items and many of those are not even building for me so I will need to do some research.

**Comment by nadvolod** [comment]
@c3ccl3ston sounds good about the others. Can you create issues for yourself to tackle based on what you think makes sense?
Also, can you please add the example to the main README. We should put all the examples there so that it's easy to find everything.

**Comment by c3ccl3ston** [comment]
Absolutely, @nadvolod! I have added the example to the main README.md and will create issues to go along with the main issue about moving java 8 as I feel is needed, to track my progress.

**Pull request merged**
