### PR TITLE
biometric login example

### PR DESCRIPTION
**Pull request by eyaly**

### CODE REVIEW

**Comment by eyaly** [comment]
> @eyaly thanks for creating this. I've mentioned this before but I know it might be confusing, so let me mention it again :) We basically have 2 types of code examples: First are tests that show off features. These are bare bones that do the minimum necessary to show off a feature. In this case, I think this is what we have. Hence, we don't use page objects or any other abstractions for such a use case. First, it introduces a lot of extra code for all of us to maintain. Second, it introduces a lot of extra complexity for the client to understand how a feature works. The second type of example is a framework, these are best practices examples that show off many features at once about Sauce Labs (parallelization, cross-platform, data driving, page objects). There are only a few frameworks. JUnit4, Junit5, TestNg and that's really it because we really have one standard for a framework. Can you please refactor these examples to remove page objects and any other functionality unnecessary to show biometric login?

@nadvolod - I deleted the page objects

**Comment by nadvolod** [comment]
@eyaly thanks so much for those updates 👍 Are you able to see the Codacy Quality Review errors by clicking on the details link?

**Comment by eyaly** [comment]
Thanks @nadvolod for sharing the Codacy Quality tool. I fixed the code syntax (except 2 changes in the sh files). Please continue with the review to merge this PR :-)

**Comment by nadvolod** [comment]
> Thanks @nadvolod for sharing the Codacy Quality tool. I fixed the code syntax (except 2 changes in the sh files). Please continue with the review to merge this PR :-)

@eyaly do you think those are stupid rules? I can ignore them in the tool

**Comment by eyaly** [comment]
@eyaly do you think those are stupid rules? I can ignore them in the tool

@nadvolod - It is not if the rules are stupid or not in this case. The curl commands in the sh files are not part of the code but this is to show the users how to copy files from local machine to Sauce storage. It is not something I can change... 
Maybe when the sh files are part of the code there is a meaning for this rule.

**Pull request merged**
